spring:
  datasource:
    driver-class-name: ${DRIVER_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  jpa:
    database: ${DATABASE}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}

    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul

  # Flyway 설정
  flyway:
    enabled: true
    baseline-on-migrate: true

--- # local
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

decorator:
  datasource:
    p6spy:
      enable-logging: true